#!/usr/bin/env ruby

unless ARGV[0]
  puts 'Usage: _bin/newpost "Post Title"'
  exit(-1)
end

date_prefix = Time.now.strftime("%Y-%m-%d")
post_name = ARGV.join ' '
permalink = post_name.strip.downcase.gsub(/[^a-zA-Z0-9]/, '-')
filename = "#{date_prefix}-#{permalink}.markdown"
post = File.expand_path("../_posts/#{filename}", File.dirname(__FILE__))

header = <<-END
---
layout: post
title: #{post_name}
author:
category:
excerpt:
---

Body text goes here...
END

File.open(post, 'w') do |f|
  f << header
end

editor = ENV['EDITOR'] || "mate"
system(editor, post)
exit(0)
