#!/usr/bin/env bash
set -euo pipefail

ignore_urls=$(cat <<'EOF' | tr '\n' ',' | sed 's/,$//'
http://localhost:4000
https://www.computerhope.com/issues/ch000549.htm
https://elixir-lang.slack.com/join/shared_invite/zt-eivteker-k_nArD59XHjjN_r8qeH6dw#/shared-invite/email
https://www.fastcompany.com/90848907/most-innovative-companies-music-2023
https://medium.com/making-change-org/our-elixir-bandit-service-e2b6af6eebc4
https://gtfs.org/
EOF
)

cache=$(cat <<'JSON'
{
  "timeframe": {
    "external": "1w",
    "internal": "1w"
  }
}
JSON
)

bundle exec htmlproofer \
  --log-level :debug \
  --ignore-urls "$ignore_urls" \
  --cache "$cache" \
  --no-check-external-hash \
  ./_site
