#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "$DIR"
source "$DIR/filter-lib.sh"

filter_errors() {
  grep -v "linking to /docs/stable/elixir/Kernel.html#%7C%3E/2, but %7C%3E/2 does not exist" |
  grep -vP "internally linking to \/docs\/.*, which does not exist" |
  grep -vP "trying to find hash of \/docs\/.*, but .* does not exist" |

  filter_more_errors |

  #delete every file hat has no error (that is, anything file that is not follow by a line starting with "  *  ")
  perl -0777 -pe 's/\- .*\n(?!\s+\*\s+)//g'
}

filter_more_errors() {
  perl -CSAD -ne '
    BEGIN {
      my $current_file = "";
    }
    if ( /^- / ) {
      $current_file = $_;
    } elsif ( $current_file =~ /getting_started/ ) {
      s/\s+\*\s+no favicon specified\n//;
    }
    print
  ' $1
}

filter_success() {
  perl -CSAD -pe "s/\|\s+Error:\s+HTML-Proofer found \d+ failures?\!//g" |
  perl -0777 -CSAD -pe "s/\n{3,}/\n\n/g"
}

filter_htmlproof() {
  filter_it "$DIR/../" "bundle exec htmlproof ./_site --file-ignore /docs/ --only-4xx --check-favicon --check-html --check-external-hash"
}

filter_htmlproof